-- SUMS DONATIONS MADE BY A DONOR AND PRINTS THEM
CREATE TRIGGER DONATION_SUMMING
  ON DONATION
  FOR INSERT, UPDATE
AS
  BEGIN

  END;

-- BACKUPS DELETED CLIENTS INTO TABLE EX_CLIENT //SHOULD USE CURSOR BCZ THERE'S NO FOR EACH ROW
CREATE TRIGGER BACKUP_CLIENT
  ON CLIENT
  FOR DELETE
AS
  BEGIN

  END;

-- 
